[package]
name = "ws-server"
version = "1.0.0"
edition = "2021"

[dependencies]
actix = "0.13.3"
actix-files = "0.6.5"
actix-rt = "2.9.0"
actix-web = "4.5.1"
actix-web-actors = "4.3.0"
env_logger = "0.11.3"
log = "0.4.21"
rand = "0.8.5"
